package moe.yo3explorer.dvb4j.model.enums;

public enum LinkageType {
    INFORMATION, EPG, CA_REPLACEMENT, TS_CONTAINING_SI, SERVICE_REPLACEMENT, DATA_BROADCAST, RCS_MAP, MOBILE_HANDOVER, SYSTEM_SOFTWARE_UPDATE, TS_CONTAINING_SSU, IP_MAC_NOTIFICATION, TS_CONTAINING_INT, EVENT_LINKAGE, EXTENDED_EVENT_LINKAGE, DOWNLOADABLE_FONT_INFO, USER_DEFINED, RESERVED
}
