package moe.yo3explorer.dvb4j.model.enums;

public enum ServiceType {
    DIGITAL_TELEVISION, DIGITAL_RADIO, TELETEXT, NVOD_REFERENCE, NVOD_TIME_SHIFTED, MOSAIC, FM_RADIO, DVB_SRM,
    ADVANCED_CODEC_DIGITAL_RADIO, H264_MOSAIC, DATA_BROADCAST, RESERVED_FOR_COMMON_INTERFACE, RCS_MAP, RCS_FLS,
    DVB_MHP, MPEG2_HD_DIGITAL_TELEVISION, H264_SD_DIGITAL_TELEVISION, H264_SD_NVOD_TIME_SHIFTED,
    H264_SD_NVOD_REFERENCE, H264_HD_DIGITAL_TELEVISION, H264_HD_NVOD_TIME_SHIFTED, H264_HD_NVOD_REFERENCE,
    H264_HD_3D_DIGITAL_TELEVISION, H264_HD_3D_NVOD_TIME_SHIFTED, H264_HD_3D_NVOD_REFERENCE, HEVC_DIGITAL_TELEVISION,
    HEVC_UHD_DIGITAL_TELEVISION, USER_DEFINED, RESERVED
}
